# -*- coding: utf-8 -*-
"""3Agentes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PloNKEHsYx6cprYFguF21KUQFLPOSy1G
"""



"""Instalación de librerías necesarias para procesamiento de datos, generación de embeddings y construcción de la base vectorial.


"""

!pip install sentence-transformers faiss-cpu pandas numpy

"""Importación de librerías"""

import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer
import faiss

"""Dataset Sobre Customer Support Tickets


"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

nombre_archivo = list(uploaded.keys())[0]

df = pd.read_csv(nombre_archivo)

print(df.shape)