# -*- coding: utf-8 -*-
"""3Agentes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PloNKEHsYx6cprYFguF21KUQFLPOSy1G
"""



"""Instalación de librerías necesarias para procesamiento de datos, generación de embeddings y construcción de la base vectorial.


"""

!pip install sentence-transformers faiss-cpu pandas numpy

"""Importación de librerías"""

import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer
import faiss

"""Dataset Sobre Customer Support Tickets


"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

nombre_archivo = list(uploaded.keys())[0]

df = pd.read_csv(nombre_archivo)

print(df.shape)

"""Agente 1: Normalizador

Carga el dataset.
Detecta valores nulos.
Detecta duplicados.
Limpia texto.
Genera un dataset limpio.
"""

import pandas as pd

class AgenteNormalizador:

    def __init__(self, archivo):
        self.archivo = archivo

    def ejecutar(self):

        df = pd.read_csv(self.archivo)

        print("===== ANALISIS INICIAL =====")
        print("Filas y columnas:", df.shape)

        print("\nValores nulos:")
        print(df.isnull().sum())

        print("\nDuplicados:")
        print(df.duplicated().sum())

        # Eliminar duplicados
        df = df.drop_duplicates()

        # Completar valores faltantes
        for columna in df.columns:

            if df[columna].dtype == "object":
                df[columna] = df[columna].fillna("No especificado")
            else:
                df[columna] = df[columna].fillna(df[columna].median())

        # Normalizar texto
        for columna in df.select_dtypes(include="object").columns:

            df[columna] = (
                df[columna]
                .astype(str)
                .str.lower()
                .str.strip()
            )

        print("\n===== DATASET NORMALIZADO =====")
        print(df.shape)

        return df


agente_normalizador = AgenteNormalizador(nombre_archivo)

df_limpio = agente_normalizador.ejecutar()

df_limpio.head()

"""Agente 2: Entrenador

Recibe el dataset limpio.
Genera embeddings con un Transformer.
Construye la base vectorial FAISS.

Crear texto para los embeddings
"""

df_limpio["texto_completo"] = (
    df_limpio["Ticket Subject"] + " " +
    df_limpio["Ticket Description"]
)

df_limpio["texto_completo"].head()

"""Instalar librerías del Agente Entrenador"""

!pip install sentence-transformers faiss-cpu -q

"""Importar librerías"""

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

"""Cargar Transformer"""

modelo = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

print("Transformer cargado correctamente")

"""Generar embeddings"""

embeddings = modelo.encode(
    df_limpio["texto_completo"].tolist(),
    show_progress_bar=True
)

print(embeddings.shape)

"""Crear Base Vectorial"""

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(
    np.array(embeddings).astype("float32")
)

print("Vectores almacenados:")
print(index.ntotal)

"""Implementar búsqueda RAG"""

consulta = "cannot login to my account"

vector_consulta = modelo.encode([consulta])

distancias, indices = index.search(
    np.array(vector_consulta).astype("float32"),
    5
)

print(indices)

"""Mostrar resultados recuperados"""

for i in indices[0]:

    print("="*60)

    print("TIPO:")
    print(df_limpio.iloc[i]["Ticket Type"])

    print("\nASUNTO:")
    print(df_limpio.iloc[i]["Ticket Subject"])

    print("\nDESCRIPCION:")
    print(df_limpio.iloc[i]["Ticket Description"])

"""Agente 3: Comunicador
Recupera información relevante.
Genera un reporte en lenguaje natural.
"""

class AgenteComunicador:

    def generar_reporte(self, df):

        print("===== REPORTE GENERAL =====")

        print("\nCantidad total de tickets:")
        print(len(df))

        print("\nTipos de ticket:")
        print(df["Ticket Type"].value_counts())

        print("\nPrioridades:")
        print(df["Ticket Priority"].value_counts())

        print("\nEstados:")
        print(df["Ticket Status"].value_counts())


comunicador = AgenteComunicador()

comunicador.generar_reporte(df_limpio)