# -*- coding: utf-8 -*-
"""3Agentes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PloNKEHsYx6cprYFguF21KUQFLPOSy1G
"""



"""Instalación de librerías necesarias para procesamiento de datos, generación de embeddings y construcción de la base vectorial.


"""

!pip install sentence-transformers faiss-cpu pandas numpy

"""Importación de librerías"""

import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer
import faiss

"""Dataset Sobre Customer Support Tickets


"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

nombre_archivo = list(uploaded.keys())[0]

df = pd.read_csv(nombre_archivo)

print(df.shape)

"""Agente 1: Normalizador

Carga el dataset.
Detecta valores nulos.
Detecta duplicados.
Limpia texto.
Genera un dataset limpio.
"""

import pandas as pd

class AgenteNormalizador:

    def __init__(self, archivo):
        self.archivo = archivo

    def ejecutar(self):

        df = pd.read_csv(self.archivo)

        print("===== ANALISIS INICIAL =====")
        print("Filas y columnas:", df.shape)

        print("\nValores nulos:")
        print(df.isnull().sum())

        print("\nDuplicados:")
        print(df.duplicated().sum())

        # Eliminar duplicados
        df = df.drop_duplicates()

        # Completar valores faltantes
        for columna in df.columns:

            if df[columna].dtype == "object":
                df[columna] = df[columna].fillna("No especificado")
            else:
                df[columna] = df[columna].fillna(df[columna].median())

        # Normalizar texto
        for columna in df.select_dtypes(include="object").columns:

            df[columna] = (
                df[columna]
                .astype(str)
                .str.lower()
                .str.strip()
            )

        print("\n===== DATASET NORMALIZADO =====")
        print(df.shape)

        return df


agente_normalizador = AgenteNormalizador(nombre_archivo)

df_limpio = agente_normalizador.ejecutar()

df_limpio.head()